---
- name: Configure the Ansible Controller
  connection: ssh
  gather_facts: True
  hosts: controller
  become: True
  roles:
    - lab_os_config
    - bertvv.dnsmasq
  tasks:
    - firewalld:
        service: dns
        permanent: yes
        state: enabled
