---
- name: Create a Lab VM on ESXi
  connection: 'local'
  gather_facts: False
  hosts: '{{ target_vm }}'
  vars_prompt:
    - name: target_esxi
      prompt: "Which ESXi server should be used?"
      private: no
    - name: target_vm
      prompt: "Which VM will be created?"
      private: no
  tasks:
    - name: Create a VM
      vmware_guest:
        hostname: '{{ target_esxi }}.{{ domain }}'
        username: 'root'
        password: '{{ root_pw }}'
        esxi_hostname : '{{ target_esxi }}.{{ domain }}'
        folder: '/ha-datacenter/vm'
        datastore: '{{ target_esxi }}_das01'
        validate_certs: '{{ validate_certs }}'
        name: '{{ target_vm }}'
        state: 'poweredoff'
        guest_id: '{{ guest_id }}'
        disk: '{{ disk_list }}'
        hardware: '{{ hardware }}'
        networks: '{{ networks }}'
      register: vm

    - name: 'VM UUID'
      debug:
        msg: '{{ target_vm }} uuid is {{ vm.instance.hw_product_uuid }}'
