# Galaxy Roles required for lab management and development
- src: nicholasrodriguez.lab_os_config
  name: lab_os_config
- src: geerlingguy.ntp
  name: geerlingguy.ntp
- src: bertvv.dnsmasq
  name: bertvv.dnsmasq
- src: nicholasrodriguez.tftp
  name: tftp
- src: nicholasrodriguez.dhcp
  name: dhcp
- src: geerlingguy.postgresql
  name: geerlingguy.postgresql
- src: nicholasrodriguez.razor
  name: razor
- src: nicholasrodriguez.razor_tasks_esxi
  name: razor_tasks_esxi
- src: nicholasrodriguez.razor_tasks_centos
  name: razor_tasks_centos
- src: nicholasrodriguez.razor_manage_hosts
  name: razor_manage_hosts
- src: geerlingguy.kubernetes
  name: geerlingguy.kubernetes
- src: geerlingguy.docker
  name: geerlingguy.docker 
