# Galaxy Roles required for lab management and development
- src: nicholasrodriguez.lab_os_config
  name: lab_os_config
- src: geerlingguy.ntp
  name: geerlingguy.ntp
- src: bertvv.dnsmasq
  name: bertvv.dnsmasq
- src: nicholasrodriguez.tftp
  name: tftp
- src: nicholasrodriguez.dhcp
  name: dhcp
- src: geerlingguy.postgresql
  name: geerlingguy.postgresql
