---
## General Vars for all Lab hosts
# Server creds
ansible_ssh_user: "{{ lookup('env','LAB_USER') }}"
remote_user: "{{ lookup('env','LAB_USER') }}"
ansible_password: "{{ lookup('env','LAB_PW') }}"
ansible_become_pass: "{{ lookup('env','LAB_PW') }}"

# Lab environment
domain: "{{ lookup('env','LAB_DOMAIN') }}"
lab_subnet: "{{ lookup('env','LAB_SUBNET') }}"
dns1: "{{ lookup('env','LAB_DNS1') }}"
dns2: "{{ lookup('env','LAB_DNS2') }}"
lab_repo: "{{ lookup('env','LAB_REPO') }}"
gateway: "{{ lab_subnet | ipaddr(1) | ipaddr('address') }}"
netmask: "{{ lab_subnet | ipaddr('netmask') }}"
user_name: "{{ lookup('env','LAB_USER') }}"

# Lab OS kickstart vars
time1: 0.uk.pool.ntp.org

# Lab OS Config Vars
ntp_enabled: True
ntp_timezone: "Europe/London"
ntp_package: "chrony"
ntp_area: "uk"
ntp_manage_config: True
ntp_servers:
  - "0{{ '.' + ntp_area if ntp_area else '' }}.pool.ntp.org iburst"
  - "1{{ '.' + ntp_area if ntp_area else '' }}.pool.ntp.org iburst"
install_gui: False

## Razor Vars
# Server OS Razor build vars
broker: "noop"
