---
## General Vars for the Ansible Controller
# Server creds
ansible_ssh_user: "{{ lookup('env','LAB_USER') }}"
remote_user: "{{ lookup('env','LAB_USER') }}"
ansible_password: "{{ lookup('env','LAB_PW') }}"
ansible_become_pass: "{{ lookup('env','LAB_PW') }}"

## Lab OS Config Vars
install_gui: True

## dnsmasq confguration
dnsmasq_listen_address: "127.0.0.1,{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
dnsmasq_upstream_servers:
    - 192.168.1.1
dnsmasq_domain: "{{ lookup('env','LAB_DOMAIN') }}"
dnsmasq_interface: "{{ ansible_default_ipv4.interface }}"
