---
## General Vars
# Server creds
ansible_ssh_user: "{{ lookup('env','LAB_USER') }}"
remote_user: "{{ lookup('env','LAB_USER') }}"
ansible_password: "{{ lookup('env','LAB_PW') }}"
ansible_become_pass: "{{ lookup('env','LAB_PW') }}"

## Razor Vars
razor_microkernel_source: "http://pup.pt/razor-microkernel-latest"
tftp_root_directory:  "/var/lib/tftpboot"
razor_db_name: "razor"
razor_db_user_name: "razor"
razor_db_user_pw: "{{ lookup('env','LAB_PW') }}"
razor_service_user: "razor"
razor_service_user_pw: "{{ lookup('env','LAB_PW') }}"
razor_api_admin: "razor_api_admin"
razor_api_admin_pw: "{{ lookup('env','LAB_PW') }}"
razor_api_roles:
  - role_name: "admin"
    role_scope: "*"
  - role_name: "user"
    role_scope: "query:*"
razor_api_users:
  - api_user_name: "razor_api_user"
    api_user_pw: "{{ lookup('env','LAB_PW') }}"
    api_user_roles: "user"

## Razor Postgres Vars
postgresql_hba_entries:
  - { type: local, database: all, user: all, auth_method: peer }
  - { type: host, database: all, user: all, address: '127.0.0.1/32', auth_method: md5 }
  - { type: host, database: all, user: all, address: '::1/128', auth_method: md5 }
postgresql_locales:
  - 'en_GB.UTF-8'
postgresql_user: postgres
postgresql_group: postgres
postgresql_databases:
  - name: "{{ razor_db_name }}"
    lc_collate: 'en_GB.UTF-8'
    lc_ctype: 'en_GB.UTF-8'
    encoding: 'UTF-8'
    template: 'template0'
    state: 'present'
postgresql_users:
  - name: "{{ razor_db_user_name }}"
    password: "{{ razor_db_user_pw }}"
    priv: ALL
    db: razor
    state: 'present'

# Centos Versions
centos_versions:
  - major: "8.3"
    build: "CentOS-8.3-dvd"
    url: "http://uk.mirrors.clouvider.net/CentOS/8.3.2011/isos/x86_64/CentOS-8.3.2011-x86_64-dvd1.iso"
  #  Older ISOs obtained from here https://vault.centos.org/8.2.2004/isos/x86_64/
  #  Its a slow public server hence uploading to lab_repo
  - major: "8.2"
    build: "CentOS-8.2-minimal"
    url: "http://{{ lab_repo }}/repo/centos/CentOS-8.2.2004-x86_64-minimal.iso"
  - major: "8.2"
    build: "CentOS-8.2-dvd"
    url: "http://{{ lab_repo }}/repo/centos/CentOS-8.2.2004-x86_64-dvd1.iso"

# ESXi Versions
esxi_versions:
  - major: "6.5"
    build: "ESXi-6.5.0-14320405"
    url: "http://{{ lab_repo }}/repo/vmware/esxi/esxi6.5/VMware-VMvisor-Installer-201908001-14320405.x86_64.iso"
  - major: "6.7"
    build: "ESXi-6.7.0-15160138"
    url: "http://{{ lab_repo }}/repo/vmware/esxi/esxi6.7/VMware-VMvisor-Installer-201912001-15160138.x86_64.iso"
  - major: "7"
    build: "ESXi-7.0.1-16850804"
    url: "http://{{ lab_repo }}/repo/vmware/esxi/esxi7/VMware-VMvisor-Installer-7.0U1-16850804.x86_64.iso"

# ESXi boot.cfg kernel parameters
# Only set this to true in non-production environments
allowLegacyCPU: true
